### ISSUE TITLE
Unit testing, job

### ISSUE THREAD

**Issue by IeuanWalker** [HangfireIO/Hangfire-Documentation#90]
Hi,

Im trying to write some unit test and verify that a hangfire job would of been created.
I've managed to this for Enqueue but can't get it to work for Scheduled.

Here is the actual implementation -

`schedule.HangfireId = _jobClient.Schedule<EmailScheduleService>(x => x.SendEmail(schedule.Id, 0, 0), schedule.ScheduleTimeUTC);`

And here is the test i have to verify the method - 

```csharp
_mockHangfireWrapper.Verify(x => x.Schedule<EmailScheduleService>(
                b => b.SendEmail(It.IsAny<int>(), It.IsAny<int>(), It.IsAny<int>()),
                It.IsAny<DateTime>()), Times.Once);
```

this is the error im getting -
```
System.NotSupportedException : Invalid verify on an extension method: x => x.Schedule<EmailScheduleService>(b => b.SendEmail(It.IsAny<int>(), It.IsAny<int>(), It.IsAny<int>()), (DateTimeOffset)It.IsAny<DateTime>())
   at Moq.Mock.ThrowIfVerifyExpressionInvolvesUnsupportedMember(Expression verify, MethodInfo method) in C:\projects\moq4\src\Moq\Mock.cs:line 778
   at Moq.Mock.VerifyNonVoid(Mock mock, LambdaExpression expression, Times times, String failMessage) in C:\projects\moq4\src\Moq\Mock.cs:line 293
   at Moq.Mock`1.Verify[TResult](Expression`1 expression, Func`1 times) in C:\projects\moq4\src\Moq\Mock.Generic.cs:line 464
   at XUnitTest.Services.EmailScheduleServiceTest.ScheduleEmail_SuccessullSchedule() in C:\WS\TS\NotificationAPI\XUnitTest\Services\EmailScheduleServiceTest.cs:line 863
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by IeuanWalker** [comment]
Sorry worked it out, just change the state on the last line (long day lol) - 

```csharp
 _mockHangfireWrapper.Verify(x => x.Create(
                It.Is<Job>(job => job.Method.Name == "SendEmail" &&
                (int)job.Args[0] == 23 &&
                (int)job.Args[2] == 1),
                It.IsAny<ScheduledState>()), Times.Once);
```
